create table transaction (
    id bigserial primary key,
    trx text,
    subTransactions text,
    appliedDateChoice text,
    isRealized boolean,
    fxRateSource text,
    targetCcy text,
    fxTable text,
    fx text,
    deals text,
    dealGroups text,
    vintageYearNames text,
    lps text,
    lpgroups text,
    splitTypes text,
    allDeals text,
    amount text,
    originalAmount text,
    appliedDate text,
    allLps text,
    impactName text,
    suid text,
    ccy text,
    gpid text,
    gahid text,
    dealAllocationRule text,
    lpAllocationRule text,
    customfields text,
    needsToSetProgressiveValues boolean,
    isPartOfAllProgressiveRuns boolean
)