do $$
begin
for count in 1..1000000 loop
        insert into message (trx,
        subTransactions,
        appliedDateChoice,
        isRealized,
        fxRateSource,
        targetCcy,
        fxTable,
        fx,
        deals,
        dealGroups,
        vintageYearNames,
        lps,
        lpgroups,
        splitTypes,
        allDeals,
        amount,
        originalAmount,
        appliedDate,
        allLps,
        impactName,
        suid,
        ccy,
        gpid,
        gahid,
        dealAllocationRule,
        lpAllocationRule,
        customfields,
        needsToSetProgressiveValues,
        isPartOfAllProgressiveRuns
        )
        values (
            concat('trx-', count),
            concat('subTransactions-', count),
            concat('appliedDateChoice-', count),
            true,
            concat('fxRateSource-', count),
            concat('targetCcy-', count),
            concat('fxTable-', count),
            concat('fx-', count),
            concat('deals-', count),
            concat('dealGroups-', count),
            concat('vintageYearNames-', count),
            concat('lps-', count),
            concat('lpgroups-', count),
            concat('splitTypes-', count),
            concat('allDeals-', count),
            concat('amount-', count),
            concat('originalAmount-', count),
            concat('appliedDate-', count),
            concat('allLps-', count),
            concat('impactName-', count),
            concat('suid-', count),
            concat('ccy-', count),
            concat('gpid-', count),
            concat('gahid-', count),
            concat('dealAllocationRule-', count),
            concat('lpAllocationRule-', count),
            concat('customfields-', count),
            true,
            true
        );
        end loop;
end;
$$;